[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "MyTorch"
version = "0.1"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy"
]
